name: bms_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.2 #A powerful HTTP package for Dart/Flutter, which supports Global settings, Interceptors, FormData, Aborting and canceling a request, Files uploading and downloading, Requests timeout, Custom adapters, etc.
  share_plus: ^6.3.1 # plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  flutter_staggered_animations: ^1.1.1 # Easily add staggered animations to your ListView, GridView, Column and Row children as shown in Material Design guidelines
  flutter_staggered_grid_view: ^0.6.2 #Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
  lottie: ^2.2.0 # Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player.
  another_flushbar: ^1.12.29 #A flexible widget for user notification. Customize your text, button, duration, animations and much more. For Android devs, it is made to replace Snackbars and Toasts.
  yaml: ^3.1.1 #A parser for YAML, a human-friendly data serialization standard
  sentry_flutter: ^6.22.0 # Sentry SDK for Flutter. This package aims to support different Flutter targets by relying on the many platforms supported by Sentry with native SDKs.
  upgrader: ^6.0.1 # Flutter package for prompting users to upgrade when there is a newer version of the app in the store.
#  firebase_core: ^2.7.1 # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
#  firebase_analytics: ^10.1.5 # Flutter plugin for Google Analytics for Firebase, an app measurement solution that provides insight on app usage and user engagement on Android and iOS.
#  firebase_messaging: ^14.2.6 # Flutter plugin for Firebase Cloud Messaging, a cross-platform messaging solution that lets you reliably deliver messages on Android and iOS.
  intl: ^0.17.0 #Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  fluttertoast: ^8.2.1 #Toast Library for Flutter, Easily create toast messages in single line of code
  flutter_form_builder: ^7.8.0 # This package helps in creation of forms in Flutter by removing the boilerplate code, reusing validation, react to changes, and collect final user input.
  form_builder_validators: ^8.5.0 # Form Builder Validators set of validators for FlutterFormBuilder. Provides common validators and a way to make your own.
  font_awesome_flutter: ^10.4.0 # [https://fontawesome.com/icons] The Font Awesome Icon pack available as Flutter Icons. Provides 1600 additional icons to use in your apps.
  expandable: ^5.0.1 # A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
  modal_bottom_sheet: ^2.1.2 # Create awesome and powerful modal bottom sheets. Material, Cupertino iOS 13 or create your own style
  device_info_plus: ^8.1.0 # Flutter plugin providing detailed information about the device (make, model, etc.), and Android or iOS version the app is running on.
  introduction_screen: ^3.1.6 # Introduction/Onboarding package for flutter app with some customizations possibilities
  flutter_secure_storage: ^8.0.0 # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  internet_connection_checker: ^1.0.0+1 #A pure Dart library that checks for internet by opening a socket to a list of specified addresses, each with individual port and timeout. Defaults are provided for convenience.
  device_preview: ^1.1.0 #Approximate how your Flutter app looks and performs on another device.
  auto_route: ^5.0.4 # AutoRoute is a declarative routing solution, where everything needed for navigation is automatically generated for you.
  pull_to_refresh: ^2.0.0 #a widget provided to the flutter scroll component drop-down refresh and pull up load.
  flutter_dotenv: ^5.0.2 #Easily configure any flutter application with global variables using a `.env` file.
  freezed: ^2.3.2 #Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed_annotation: ^2.2.0 # Annotations for the freezed code-generator. This package does nothing without freezed too.
  json_annotation: ^4.8.0 # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  flutter_launcher_icons: ^0.12.0 #A package which simplifies the task of updating your Flutter app's launcher icon.
  hooks_riverpod: ^2.3.1 # A simple way to access state from anywhere in your application while robust and testable.
  cupertino_icons: ^1.0.2 # The following adds the Cupertino Icons font to your application. Use with the CupertinoIcons class for iOS style icons.
  flutter_svg: ^2.0.3 #An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.



#to change app launcher icon add following section
flutter_icons:
  image_path: "assets/images/launcher_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # run :
  #  1 : flutter pub get
  #  2 : flutter pub run flutter_launcher_icons:main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # The "flutter_lints" package below contains a set of recommended lints to  encourage good coding practices.
  build_runner: ^2.3.3 # A build system for Dart code generation and modular compilation.
  json_serializable: ^6.6.1 #Automatically generate code for converting to and from JSON by annotating Dart classes.
  riverpod_generator: ^2.1.3 #A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  auto_route_generator: ^5.0.3 #AutoRoute is a declartive routing solution, where everything needed for navigation is automatically generated for you.

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/svg/
    - assets/gif/
    - assets/.env
    - assets/anim/
    - pubspec.yaml

